version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.11

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  deploy:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: sudo npm install -g firebase-tools
      - run:
          name: Setup Service Account
          command: echo $FIREBASE_SERVICE_ACCOUNT > $HOME/serviceAccount.json
      - run:
          name: Deploy to Firebase
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccount.json
            firebase deploy --only hosting --non-interactive

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
